#pragma once
#include <string>
#include <iostream>
#include <charconv>

char ascii_int_to_char(int i){
    return char(i);
}
int char_to_ascii_int(char c){
    int c_int = int(c);
    if (c_int < 0)
        c_int = 256 + c_int;
    return c_int;
}
std::string get_escpaed_string_from_char(char c)
{
    int c_int = char_to_ascii_int(c);
    switch (c_int)
    {
    case 0:
        return "\\x00";
    case 1:
        return "\\x01";
    case 2:
        return "\\x02";
    case 3:
        return "\\x03";
    case 4:
        return "\\x04";
    case 5:
        return "\\x05";
    case 6:
        return "\\x06";
    case 7:
        return "\\x07";
    case 8:
        return "\\x08";
    case 9:
        return "\\t";
    case 10:
        return "\\n";
    case 11:
        return "\\v";
    case 12:
        return "\\f";
    case 13:
        return "\\r";
    case 14:
        return "\\x0e";
    case 15:
        return "\\x0f";
    case 16:
        return "\\x10";
    case 17:
        return "\\x11";
    case 18:
        return "\\x12";
    case 19:
        return "\\x13";
    case 20:
        return "\\x14";
    case 21:
        return "\\x15";
    case 22:
        return "\\x16";
    case 23:
        return "\\x17";
    case 24:
        return "\\x18";
    case 25:
        return "\\x19";
    case 26:
        return "\\x1a";
    case 27:
        return "\\x1b";
    case 28:
        return "\\x1c";
    case 29:
        return "\\x1d";
    case 30:
        return "\\x1e";
    case 31:
        return "\\x1f";
    case 32:
        return " ";
    case 33:
        return "!";
    case 34:
        return "\\\"";
    case 35:
        return "#";
    case 36:
        return "\$";
    case 37:
        return "%";
    case 38:
        return "&";
    case 39:
        return "'";
    case 40:
        return "(";
    case 41:
        return ")";
    case 42:
        return "*";
    case 43:
        return "+";
    case 44:
        return ",";
    case 45:
        return "-";
    case 46:
        return ".";
    case 47:
        return "/";
    case 48:
        return "0";
    case 49:
        return "1";
    case 50:
        return "2";
    case 51:
        return "3";
    case 52:
        return "4";
    case 53:
        return "5";
    case 54:
        return "6";
    case 55:
        return "7";
    case 56:
        return "8";
    case 57:
        return "9";
    case 58:
        return ":";
    case 59:
        return ";";
    case 60:
        return "<";
    case 61:
        return "=";
    case 62:
        return ">";
    case 63:
        return "?";
    case 64:
        return "@";
    case 65:
        return "A";
    case 66:
        return "B";
    case 67:
        return "C";
    case 68:
        return "D";
    case 69:
        return "E";
    case 70:
        return "F";
    case 71:
        return "G";
    case 72:
        return "H";
    case 73:
        return "I";
    case 74:
        return "J";
    case 75:
        return "K";
    case 76:
        return "L";
    case 77:
        return "M";
    case 78:
        return "N";
    case 79:
        return "O";
    case 80:
        return "P";
    case 81:
        return "Q";
    case 82:
        return "R";
    case 83:
        return "S";
    case 84:
        return "T";
    case 85:
        return "U";
    case 86:
        return "V";
    case 87:
        return "W";
    case 88:
        return "X";
    case 89:
        return "Y";
    case 90:
        return "Z";
    case 91:
        return "[";
    case 92:
        return "\\";
    case 93:
        return "]";
    case 94:
        return "^";
    case 95:
        return "_";
    case 96:
        return "`";
    case 97:
        return "a";
    case 98:
        return "b";
    case 99:
        return "c";
    case 100:
        return "d";
    case 101:
        return "e";
    case 102:
        return "f";
    case 103:
        return "g";
    case 104:
        return "h";
    case 105:
        return "i";
    case 106:
        return "j";
    case 107:
        return "k";
    case 108:
        return "l";
    case 109:
        return "m";
    case 110:
        return "n";
    case 111:
        return "o";
    case 112:
        return "p";
    case 113:
        return "q";
    case 114:
        return "r";
    case 115:
        return "s";
    case 116:
        return "t";
    case 117:
        return "u";
    case 118:
        return "v";
    case 119:
        return "w";
    case 120:
        return "x";
    case 121:
        return "y";
    case 122:
        return "z";
    case 123:
        return "{";
    case 124:
        return "|";
    case 125:
        return "}";
    case 126:
        return "~";
    case 127:
        return "\\x7f";
    case 128:
        return "\\x80";
    case 129:
        return "\\x81";
    case 130:
        return "\\x82";
    case 131:
        return "\\x83";
    case 132:
        return "\\x84";
    case 133:
        return "\\x85";
    case 134:
        return "\\x86";
    case 135:
        return "\\x87";
    case 136:
        return "\\x88";
    case 137:
        return "\\x89";
    case 138:
        return "\\x8a";
    case 139:
        return "\\x8b";
    case 140:
        return "\\x8c";
    case 141:
        return "\\x8d";
    case 142:
        return "\\x8e";
    case 143:
        return "\\x8f";
    case 144:
        return "\\x90";
    case 145:
        return "\\x91";
    case 146:
        return "\\x92";
    case 147:
        return "\\x93";
    case 148:
        return "\\x94";
    case 149:
        return "\\x95";
    case 150:
        return "\\x96";
    case 151:
        return "\\x97";
    case 152:
        return "\\x98";
    case 153:
        return "\\x99";
    case 154:
        return "\\x9a";
    case 155:
        return "\\x9b";
    case 156:
        return "\\x9c";
    case 157:
        return "\\x9d";
    case 158:
        return "\\x9e";
    case 159:
        return "\\x9f";
    case 160:
        return "\\xa0";
    case 161:
        return "\\xa1";
    case 162:
        return "\\xa2";
    case 163:
        return "\\xa3";
    case 164:
        return "\\xa4";
    case 165:
        return "\\xa5";
    case 166:
        return "\\xa6";
    case 167:
        return "\\xa7";
    case 168:
        return "\\xa8";
    case 169:
        return "\\xa9";
    case 170:
        return "\\xaa";
    case 171:
        return "\\xab";
    case 172:
        return "\\xac";
    case 173:
        return "\\xad";
    case 174:
        return "\\xae";
    case 175:
        return "\\xaf";
    case 176:
        return "\\xb0";
    case 177:
        return "\\xb1";
    case 178:
        return "\\xb2";
    case 179:
        return "\\xb3";
    case 180:
        return "\\xb4";
    case 181:
        return "\\xb5";
    case 182:
        return "\\xb6";
    case 183:
        return "\\xb7";
    case 184:
        return "\\xb8";
    case 185:
        return "\\xb9";
    case 186:
        return "\\xba";
    case 187:
        return "\\xbb";
    case 188:
        return "\\xbc";
    case 189:
        return "\\xbd";
    case 190:
        return "\\xbe";
    case 191:
        return "\\xbf";
    case 192:
        return "\\xc0";
    case 193:
        return "\\xc1";
    case 194:
        return "\\xc2";
    case 195:
        return "\\xc3";
    case 196:
        return "\\xc4";
    case 197:
        return "\\xc5";
    case 198:
        return "\\xc6";
    case 199:
        return "\\xc7";
    case 200:
        return "\\xc8";
    case 201:
        return "\\xc9";
    case 202:
        return "\\xca";
    case 203:
        return "\\xcb";
    case 204:
        return "\\xcc";
    case 205:
        return "\\xcd";
    case 206:
        return "\\xce";
    case 207:
        return "\\xcf";
    case 208:
        return "\\xd0";
    case 209:
        return "\\xd1";
    case 210:
        return "\\xd2";
    case 211:
        return "\\xd3";
    case 212:
        return "\\xd4";
    case 213:
        return "\\xd5";
    case 214:
        return "\\xd6";
    case 215:
        return "\\xd7";
    case 216:
        return "\\xd8";
    case 217:
        return "\\xd9";
    case 218:
        return "\\xda";
    case 219:
        return "\\xdb";
    case 220:
        return "\\xdc";
    case 221:
        return "\\xdd";
    case 222:
        return "\\xde";
    case 223:
        return "\\xdf";
    case 224:
        return "\\xe0";
    case 225:
        return "\\xe1";
    case 226:
        return "\\xe2";
    case 227:
        return "\\xe3";
    case 228:
        return "\\xe4";
    case 229:
        return "\\xe5";
    case 230:
        return "\\xe6";
    case 231:
        return "\\xe7";
    case 232:
        return "\\xe8";
    case 233:
        return "\\xe9";
    case 234:
        return "\\xea";
    case 235:
        return "\\xeb";
    case 236:
        return "\\xec";
    case 237:
        return "\\xed";
    case 238:
        return "\\xee";
    case 239:
        return "\\xef";
    case 240:
        return "\\xf0";
    case 241:
        return "\\xf1";
    case 242:
        return "\\xf2";
    case 243:
        return "\\xf3";
    case 244:
        return "\\xf4";
    case 245:
        return "\\xf5";
    case 246:
        return "\\xf6";
    case 247:
        return "\\xf7";
    case 248:
        return "\\xf8";
    case 249:
        return "\\xf9";
    case 250:
        return "\\xfa";
    case 251:
        return "\\xfb";
    case 252:
        return "\\xfc";
    case 253:
        return "\\xfd";
    case 254:
        return "\\xfe";
    case 255:
        return "\\xff";
    default:
        std::cout << "char:" << c_int << std::endl;
        assert(0 && "Invalid character");
    }
}